### ISSUE TITLE
Hi :3

### ISSUE THREAD

**Issue by NgLam2911** [jaylac2000/PlayerLevels#1]
I am really like you if you folked my project in https://github.com/LamPocketVN/PlayerLevelAPI to edit and update code :3

**Comment by jaylac2000** [comment]
i didnt edit any code just translated to English in the messages file

**Comment by NgLam2911** [comment]
Ahh Thanks, but I think you have translate Vietnamese language to English not correctly:3

**Comment by NgLam2911** [comment]
Next update i will fix that :D

**Comment by NgLam2911** [comment]
Your not a high enough level ->
you not have enough levels to break this block :3
